services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  logger:
    build: ./
    container_name: app
    ports:
      - "8050:8050"
    depends_on:
      - redis
